<a href="https://colab.research.google.com/github/HK25abm/Transformer-Phishing-Detection/blob/main/Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Enron
enron = pd.read_csv("emails.csv")

# CEAS
ceas = pd.read_csv("CEAS_08.csv")

# Modern phishing
phishing = pd.read_csv("phishing.csv")

# Mixed dataset
paper2 = pd.read_csv("Phishing_Email.csv")

# Optional
legit = pd.read_csv("legit.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'emails.csv'

In [3]:
import pandas as pd

try:
    enron = pd.read_csv("emails.csv")
except Exception as e:
    print(e)

Error tokenizing data. C error: EOF inside string starting at row 92286

In [2]:
import pandas as pd

# Enron
enron = pd.read_csv("emails.csv")

# CEAS
ceas = pd.read_csv("CEAS_08.csv")

# Modern phishing
phishing = pd.read_csv("phishing.csv")

# Mixed dataset
paper2 = pd.read_csv("Phishing_Email.csv")

# Optional
legit = pd.read_csv("legit.csv")

In [3]:
enron = enron.rename(
    columns={
        "message":"text"
    }
)

In [4]:
enron = enron[
    ["text"]
]

In [5]:
enron = enron.dropna()

enron = enron.drop_duplicates()

In [6]:
enron["label"] = 0

enron["source"] = "Enron"

enron["urls"] = 0

In [7]:
SEED = 42

enron = enron.sample(
    n=10000,
    random_state=SEED
)

In [8]:
ceas["text"] = (
    ceas["subject"].fillna("")
    + " "
    + ceas["body"].fillna("")
)

In [9]:
ceas = ceas[
    ceas["label"] == 1
]

In [10]:
ceas = ceas[
    [
        "text",
        "label",
        "urls"
    ]
]

In [11]:
ceas["source"] = "CEAS"

In [12]:
phishing["text"] = (
    phishing["subject"].fillna("")
    + " "
    + phishing["body"].fillna("")
)

In [13]:
phishing["source"] = "Modern"

In [14]:
paper2 = paper2.rename(
    columns={
        "Email Text":"text"
    }
)

In [15]:
paper2["label"] = paper2["Email Type"].map({
    "Safe Email":0,
    "Phishing Email":1
})

In [16]:
paper2 = paper2[
    paper2["label"] == 1
]

In [17]:
paper2["urls"] = 0

In [18]:
paper2 = paper2[
    [
        "text",
        "label",
        "urls"
    ]
]

In [19]:
paper2["source"] = "Paper2"

In [20]:
final_df = pd.concat(
    [
        enron,
        ceas,
        phishing,
        paper2
    ],
    ignore_index=True
)

In [21]:
final_df = final_df.drop_duplicates(
    subset=["text"]
)

final_df = final_df.dropna(
    subset=["text"]
)

In [24]:
print(final_df["label"].value_counts())

print(final_df["source"].value_counts())

label
0    10000
1    10000
Name: count, dtype: int64
source
Enron     10000
CEAS       7588
Paper2     2237
Modern      175
Name: count, dtype: int64

In [23]:
legitimate = final_df[
    final_df["label"] == 0
]

phishing = final_df[
    final_df["label"] == 1
]

phishing = phishing.sample(
    n=10000,
    random_state=42
)

final_df = pd.concat(
    [
        legitimate,
        phishing
    ]
)

In [25]:
final_df = final_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [26]:
final_df["sample_id"] = [
    f"EMAIL_{i:06d}"
    for i in range(
        1,
        len(final_df)+1
    )
]

In [27]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    final_df,
    test_size=0.30,
    stratify=final_df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

In [28]:
train_df.to_csv(
    "train.csv",
    index=False
)

val_df.to_csv(
    "validation.csv",
    index=False
)

test_df.to_csv(
    "test.csv",
    index=False
)

final_df.to_csv(
    "Final_Phishing_Email_Dataset.csv",
    index=False
)

In [29]:
final_df.to_csv(
    "Final_Phishing_Email_Dataset.csv",
    index=False
)

In [30]:
train_df.to_csv(
    "train.csv",
    index=False
)

val_df.to_csv(
    "validation.csv",
    index=False
)

test_df.to_csv(
    "test.csv",
    index=False
)

In [31]:
summary = {
    "Dataset": [
        "Final Dataset",
        "Training",
        "Validation",
        "Testing"
    ],
    "Samples": [
        len(final_df),
        len(train_df),
        len(val_df),
        len(test_df)
    ]
}

import pandas as pd

summary_df = pd.DataFrame(summary)

summary_df.to_csv(
    "dataset_summary.csv",
    index=False
)

summary_df

         Dataset  Samples
0  Final Dataset    20000
1       Training    14000
2     Validation     3000
3        Testing     3000

In [32]:
summary = {
    "Dataset": [
        "Final Dataset",
        "Training",
        "Validation",
        "Testing"
    ],
    "Samples": [
        len(final_df),
        len(train_df),
        len(val_df),
        len(test_df)
    ]
}

import pandas as pd

summary_df = pd.DataFrame(summary)

summary_df.to_csv(
    "dataset_summary.csv",
    index=False
)

summary_df

         Dataset  Samples
0  Final Dataset    20000
1       Training    14000
2     Validation     3000
3        Testing     3000

In [33]:
import os

print(os.listdir())

['.config', 'legit.csv', 'emails.csv', 'test.csv', 'validation.csv', 'dataset_summary.csv', 'phishing.csv', 'Final_Phishing_Email_Dataset.csv', 'train.csv', 'Phishing_Email.csv', 'CEAS_08.csv', 'sample_data']