<a href="https://colab.research.google.com/github/HK25abm/Transformer-Phishing-Detection/blob/main/Final_Dataset_Rebuild.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
SEED = 42

In [3]:
SEED = 42

In [4]:
enron_raw = pd.read_csv(
    "emails.csv",
    engine="python",
    on_bad_lines="skip"
)

ceas_raw = pd.read_csv("CEAS_08.csv")
modern_raw = pd.read_csv("phishing.csv")
paper2_raw = pd.read_csv("Phishing_Email.csv")

In [5]:
print("Enron:", enron_raw.shape)
print("CEAS:", ceas_raw.shape)
print("Modern:", modern_raw.shape)
print("Paper2:", paper2_raw.shape)

Enron: (843222, 2)
CEAS: (39154, 7)
Modern: (1000, 7)
Paper2: (18650, 3)

In [6]:
print("Enron columns:", enron_raw.columns.tolist())
print("CEAS columns:", ceas_raw.columns.tolist())
print("Modern columns:", modern_raw.columns.tolist())
print("Paper2 columns:", paper2_raw.columns.tolist())

Enron columns: ['file', 'message']
CEAS columns: ['sender', 'receiver', 'date', 'subject', 'body', 'label', 'urls']
Modern columns: ['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']
Paper2 columns: ['Unnamed: 0', 'Email Text', 'Email Type']

In [7]:
enron = enron_raw.rename(
    columns={"message": "text"}
).copy()

enron = enron[["text"]]

enron["label"] = 0
enron["source"] = "Enron"
enron["email_type"] = "legitimate"
enron["urls"] = 0

In [8]:
paper2 = paper2_raw.rename(
    columns={
        "Email Text": "text",
        "Email Type": "email_type_original"
    }
).copy()

In [9]:
paper2["label"] = paper2["email_type_original"].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

In [10]:
paper2["label"] = paper2["email_type_original"].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

In [11]:
paper2["email_type"] = paper2["label"].map({
    0: "legitimate",
    1: "phishing"
})

In [12]:
paper2["email_type"] = paper2["label"].map({
    0: "legitimate",
    1: "phishing"
})

In [13]:
paper2 = paper2[
    ["text", "label", "source", "email_type", "urls"]
]

KeyError: "['source', 'urls'] not in index"

In [14]:
print(paper2["label"].value_counts(dropna=False))

label
0    11322
1     7328
Name: count, dtype: int64

In [15]:
print(paper2.columns.tolist())

['Unnamed: 0', 'text', 'email_type_original', 'label', 'email_type']

In [16]:
paper2["source"] = "Paper2"
paper2["urls"] = 0

In [17]:
print(paper2.columns.tolist())

['Unnamed: 0', 'text', 'email_type_original', 'label', 'email_type', 'source', 'urls']

In [18]:
paper2 = paper2[
    ["text", "label", "source", "email_type", "urls"]
]

In [19]:
paper2.head()

,text,label,source,email_type,urls
0,"re : 6 . 1100 , disc : uniformitarianism , re ...",0,Paper2,legitimate,0
1,the other side of * galicismos * * galicismo *...,0,Paper2,legitimate,0
2,re : equistar deal tickets are you still avail...,0,Paper2,legitimate,0
3,\nHello I am your hot lil horny toy.\n I am...,1,Paper2,phishing,0
4,software at incredibly low prices ( 86 % lower...,1,Paper2,phishing,0

In [20]:
paper2 = paper2_raw.rename(
    columns={
        "Email Text": "text",
        "Email Type": "email_type_original"
    }
).copy()

paper2["label"] = paper2["email_type_original"].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

paper2["source"] = "Paper2"
paper2["urls"] = 0

paper2["email_type"] = paper2["label"].map({
    0: "legitimate",
    1: "phishing"
})

paper2 = paper2[
    ["text", "label", "source", "email_type", "urls"]
]

print(paper2.shape)
print(paper2["label"].value_counts(dropna=False))
paper2.head()

(18650, 5)
label
0    11322
1     7328
Name: count, dtype: int64

,text,label,source,email_type,urls
0,"re : 6 . 1100 , disc : uniformitarianism , re ...",0,Paper2,legitimate,0
1,the other side of * galicismos * * galicismo *...,0,Paper2,legitimate,0
2,re : equistar deal tickets are you still avail...,0,Paper2,legitimate,0
3,\nHello I am your hot lil horny toy.\n I am...,1,Paper2,phishing,0
4,software at incredibly low prices ( 86 % lower...,1,Paper2,phishing,0

In [21]:
ceas = ceas_raw.copy()

ceas["text"] = (
    ceas["subject"].fillna("").astype(str)
    + " "
    + ceas["body"].fillna("").astype(str)
)

ceas = ceas[
    ceas["label"] == 1
].copy()

ceas["source"] = "CEAS"
ceas["email_type"] = "phishing"

if "urls" not in ceas.columns:
    ceas["urls"] = 0

ceas = ceas[
    ["text", "label", "source", "email_type", "urls"]
]

print(ceas.shape)
print(ceas["label"].value_counts())
ceas.head()

(21842, 5)
label
1    21842
Name: count, dtype: int64

,text,label,source,email_type,urls
0,"Never agree to be a loser Buck up, your troubl...",1,CEAS,phishing,1
1,Befriend Jenna Jameson \nUpgrade your sex and ...,1,CEAS,phishing,1
2,CNN.com Daily Top 10 >+=+=+=+=+=+=+=+=+=+=+=+=...,1,CEAS,phishing,1
4,SpecialPricesPharmMoreinfo \nWelcomeFastShippi...,1,CEAS,phishing,1
5,From Caroline Aragon \n\n\n\n\nYo wu urS mo ou...,1,CEAS,phishing,0

In [22]:
ceas = ceas_raw.copy()

ceas["text"] = (
    ceas["subject"].fillna("").astype(str)
    + " "
    + ceas["body"].fillna("").astype(str)
)

ceas = ceas[
    ceas["label"] == 1
].copy()

ceas["source"] = "CEAS"
ceas["email_type"] = "phishing"

if "urls" not in ceas.columns:
    ceas["urls"] = 0

ceas = ceas[
    ["text", "label", "source", "email_type", "urls"]
]

print(ceas.shape)
print(ceas["label"].value_counts())
ceas.head()

(21842, 5)
label
1    21842
Name: count, dtype: int64

,text,label,source,email_type,urls
0,"Never agree to be a loser Buck up, your troubl...",1,CEAS,phishing,1
1,Befriend Jenna Jameson \nUpgrade your sex and ...,1,CEAS,phishing,1
2,CNN.com Daily Top 10 >+=+=+=+=+=+=+=+=+=+=+=+=...,1,CEAS,phishing,1
4,SpecialPricesPharmMoreinfo \nWelcomeFastShippi...,1,CEAS,phishing,1
5,From Caroline Aragon \n\n\n\n\nYo wu urS mo ou...,1,CEAS,phishing,0

In [23]:
print(enron.columns.tolist())
print(enron["label"].value_counts())
enron.head()

['text', 'label', 'source', 'email_type', 'urls']
label
0    843222
Name: count, dtype: int64

,text,label,source,email_type,urls
0,Message-ID: <18782981.1075855378110.JavaMail.e...,0,Enron,legitimate,0
1,Message-ID: <15464986.1075855378456.JavaMail.e...,0,Enron,legitimate,0
2,Message-ID: <24216240.1075855687451.JavaMail.e...,0,Enron,legitimate,0
3,Message-ID: <13505866.1075863688222.JavaMail.e...,0,Enron,legitimate,0
4,Message-ID: <30922949.1075863688243.JavaMail.e...,0,Enron,legitimate,0

In [24]:
import re

def clean_email_text(text):
    text = str(text)

    parts = re.split(r"\n\s*\n", text, maxsplit=1)

    if len(parts) == 2:
        header, body = parts

        subject_match = re.search(
            r"(?im)^subject:\s*(.*)$",
            header
        )

        subject = (
            subject_match.group(1).strip()
            if subject_match
            else ""
        )

        text = f"{subject} {body}"

    text = re.sub(
        r"(?im)^(message-id|from|to|date|mime-version|content-type|content-transfer-encoding):.*$",
        " ",
        text
    )

    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"[\r\n\t]+", " ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [25]:
for frame in [enron, paper2, ceas, modern]:
    frame["text"] = frame["text"].apply(clean_email_text)

NameError: name 'modern' is not defined

In [26]:
print("Enron exists:", "enron" in globals())
print("Paper2 exists:", "paper2" in globals())
print("CEAS exists:", "ceas" in globals())
print("Modern exists:", "modern" in globals())

Enron exists: True
Paper2 exists: True
CEAS exists: True
Modern exists: False

In [27]:
modern = modern_raw.copy()

modern["text"] = (
    modern["subject"].fillna("").astype(str)
    + " "
    + modern["body"].fillna("").astype(str)
)

modern = modern[modern["label"] == 1].copy()

modern["source"] = "Modern"
modern["email_type"] = "phishing"

if "urls" not in modern.columns:
    modern["urls"] = 0

modern = modern[
    ["text", "label", "source", "email_type", "urls"]
]

print(modern.shape)
modern.head()

(1000, 5)

,text,label,source,email_type,urls
0,Your MetaMask wallet will be suspended Verify ...,1,Modern,phishing,1
1,Your MetaMask wallet will be suspended Verify ...,1,Modern,phishing,1
2,Your shipment is on the way Announcing JotForm...,1,Modern,phishing,1
3,Your shipment is on the way Announcing JotForm...,1,Modern,phishing,1
4,Netflix : We're having some trouble with your ...,1,Modern,phishing,1

In [28]:
for frame in [enron, paper2, ceas, modern]:
    frame["text"] = frame["text"].apply(clean_email_text)

In [29]:
print(modern_raw.columns.tolist())

['sender', 'receiver', 'date', 'subject', 'body', 'urls', 'label']

In [30]:
modern = modern_raw.copy()

modern["text"] = (
    modern["subject"].fillna("").astype(str)
    + " "
    + modern["body"].fillna("").astype(str)
)

# Keep only phishing emails
modern = modern[modern["label"] == 1].copy()

modern["source"] = "Modern"
modern["email_type"] = "phishing"

modern = modern[
    ["text", "label", "source", "email_type", "urls"]
]

print(modern.shape)
modern.head()

(1000, 5)

,text,label,source,email_type,urls
0,Your MetaMask wallet will be suspended Verify ...,1,Modern,phishing,1
1,Your MetaMask wallet will be suspended Verify ...,1,Modern,phishing,1
2,Your shipment is on the way Announcing JotForm...,1,Modern,phishing,1
3,Your shipment is on the way Announcing JotForm...,1,Modern,phishing,1
4,Netflix : We're having some trouble with your ...,1,Modern,phishing,1

In [31]:
for frame in [enron, paper2, ceas, modern]:
    frame["text"] = frame["text"].apply(clean_email_text)

In [32]:
 enron = clean_frame(enron)
paper2 = clean_frame(paper2)
ceas = clean_frame(ceas)
modern = clean_frame(modern)

print("Enron:", len(enron))
print("Paper2:", len(paper2))
print("CEAS:", len(ceas))
print("Modern:", len(modern))

NameError: name 'clean_frame' is not defined

In [33]:
def clean_frame(frame):
    frame = frame.copy()

    # Remove missing text or labels
    frame = frame.dropna(subset=["text", "label"])

    # Clean text
    frame["text"] = frame["text"].astype(str).str.strip()

    # Remove very short emails
    frame = frame[frame["text"].str.len() >= 20]

    # Ensure labels are integers
    frame["label"] = frame["label"].astype(int)

    # Keep only binary labels
    frame = frame[frame["label"].isin([0, 1])]

    # Remove duplicate emails
    frame = frame.drop_duplicates(subset=["text"])

    frame = frame.reset_index(drop=True)

    return frame

In [34]:
enron = clean_frame(enron)
paper2 = clean_frame(paper2)
ceas = clean_frame(ceas)
modern = clean_frame(modern)

print("Enron :", len(enron))
print("Paper2:", len(paper2))
print("CEAS  :", len(ceas))
print("Modern:", len(modern))

Enron : 257916
Paper2: 17437
CEAS  : 16929
Modern: 497

In [35]:
paper2_safe = paper2[
    paper2["label"] == 0
].copy()

paper2_phishing = paper2[
    paper2["label"] == 1
].copy()

print("Paper2 safe:", len(paper2_safe))
print("Paper2 phishing:", len(paper2_phishing))

Paper2 safe: 10940
Paper2 phishing: 6497

In [36]:
SEED = 42

enron_sample = enron.sample(
    n=8000,
    random_state=SEED
)

paper2_safe_sample = paper2_safe.sample(
    n=2000,
    random_state=SEED
)

ceas_sample = ceas.sample(
    n=6000,
    random_state=SEED
)

modern_sample = modern.sample(
    n=len(modern),
    random_state=SEED
)

paper2_phishing_needed = (
    10000
    - len(ceas_sample)
    - len(modern_sample)
)

paper2_phishing_sample = paper2_phishing.sample(
    n=paper2_phishing_needed,
    random_state=SEED
)

print("Paper2 phishing selected:", len(paper2_phishing_sample))

Paper2 phishing selected: 3503

In [37]:
master_df = pd.concat(
    [
        enron_sample,
        paper2_safe_sample,
        ceas_sample,
        paper2_phishing_sample,
        modern_sample
    ],
    ignore_index=True
)

In [38]:
print(master_df.shape)

print(
    pd.crosstab(
        master_df["source"],
        master_df["label"],
        margins=True
    )
)

(20000, 5)
label       0      1    All
source
CEAS        0   6000   6000
Enron    8000      0   8000
Modern      0    497    497
Paper2   2000   3503   5503
All     10000  10000  20000

In [39]:
before = len(master_df)

master_df = master_df.drop_duplicates(
    subset=["text"]
).reset_index(drop=True)

after = len(master_df)

print("Duplicates removed:", before - after)
print(master_df["label"].value_counts())

Duplicates removed: 0
label
0    10000
1    10000
Name: count, dtype: int64

In [40]:
legitimate_df = master_df[
    master_df["label"] == 0
]

phishing_df = master_df[
    master_df["label"] == 1
]

target_count = min(
    len(legitimate_df),
    len(phishing_df)
)

legitimate_df = legitimate_df.sample(
    n=target_count,
    random_state=SEED
)

phishing_df = phishing_df.sample(
    n=target_count,
    random_state=SEED
)

master_df = pd.concat(
    [legitimate_df, phishing_df],
    ignore_index=True
)

master_df = master_df.sample(
    frac=1,
    random_state=SEED
).reset_index(drop=True)

In [41]:
master_df["sample_id"] = [
    f"EMAIL_{i:06d}"
    for i in range(1, len(master_df) + 1)
]

In [42]:
master_df["sample_id"] = [
    f"EMAIL_{i:06d}"
    for i in range(1, len(master_df) + 1)
]

In [43]:
print("Final shape:", master_df.shape)

print("\nClass distribution:")
print(master_df["label"].value_counts())

print("\nSource and label distribution:")
print(
    pd.crosstab(
        master_df["source"],
        master_df["label"],
        margins=True
    )
)

Final shape: (20000, 6)

Class distribution:
label
1    10000
0    10000
Name: count, dtype: int64

Source and label distribution:
label       0      1    All
source
CEAS        0   6000   6000
Enron    8000      0   8000
Modern      0    497    497
Paper2   2000   3503   5503
All     10000  10000  20000

In [44]:
master_df["stratify_key"] = (
    master_df["source"].astype(str)
    + "_"
    + master_df["label"].astype(str)
)

In [45]:
print(master_df["stratify_key"].value_counts())

stratify_key
Enron_0     8000
CEAS_1      6000
Paper2_1    3503
Paper2_0    2000
Modern_1     497
Name: count, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    master_df,
    test_size=0.30,
    random_state=SEED,
    stratify=master_df["stratify_key"]
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=SEED,
    stratify=temp_df["stratify_key"]
)

In [47]:
for frame in [train_df, val_df, test_df]:
    frame.drop(
        columns=["stratify_key"],
        inplace=True
    )

    frame.reset_index(
        drop=True,
        inplace=True
    )

In [48]:
print(
    "Train–validation overlap:",
    len(set(train_df["text"]) & set(val_df["text"]))
)

print(
    "Train–test overlap:",
    len(set(train_df["text"]) & set(test_df["text"]))
)

print(
    "Validation–test overlap:",
    len(set(val_df["text"]) & set(test_df["text"]))
)

Train–validation overlap: 0
Train–test overlap: 0
Validation–test overlap: 0

In [49]:
for name, frame in {
    "Train": train_df,
    "Validation": val_df,
    "Test": test_df
}.items():
    print(f"\n{name}: {frame.shape}")

    print(frame["label"].value_counts())

    print(
        pd.crosstab(
            frame["source"],
            frame["label"],
            margins=True
        )
    )

Train: (14000, 6)
label
0    7000
1    7000
Name: count, dtype: int64
label      0     1    All
source
CEAS       0  4200   4200
Enron   5600     0   5600
Modern     0   348    348
Paper2  1400  2452   3852
All     7000  7000  14000

Validation: (3000, 6)
label
1    1500
0    1500
Name: count, dtype: int64
label      0     1   All
source
CEAS       0   900   900
Enron   1200     0  1200
Modern     0    74    74
Paper2   300   526   826
All     1500  1500  3000

Test: (3000, 6)
label
0    1500
1    1500
Name: count, dtype: int64
label      0     1   All
source
CEAS       0   900   900
Enron   1200     0  1200
Modern     0    75    75
Paper2   300   525   825
All     1500  1500  3000

In [50]:
master_df.to_csv(
    "Final_Phishing_Email_Dataset_v2.csv",
    index=False
)

train_df.to_csv(
    "train_v2.csv",
    index=False
)

val_df.to_csv(
    "validation_v2.csv",
    index=False
)

test_df.to_csv(
    "test_v2.csv",
    index=False
)